import Head from 'next/head'
import React, { ReactElement } from 'react'
import Layout from '../components/layout'
import { SITE_NAME } from '../util/constants'

export default function Home(): ReactElement {
  return (
    <div>
      <Head>
        <title>Home | {SITE_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout></Layout>
    </div>
  )
}
